# coding: utf-8

"""
    DialMyCalls API

    The DialMyCalls API

    OpenAPI spec version: 2.0.1
    Contact: support@dialmycalls.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import dialmycalls_client
from dialmycalls_client.rest import ApiException
from dialmycalls_client.apis.texts_api import TextsApi


class TestTextsApi(unittest.TestCase):
    """ TextsApi unit test stubs """

    def setUp(self):
        self.api = dialmycalls_client.apis.texts_api.TextsApi()

    def tearDown(self):
        pass

    def test_cancel_text_by_id(self):
        """
        Test case for cancel_text_by_id

        Cancel Text
        """
        pass

    def test_create_text(self):
        """
        Test case for create_text

        Create Text
        """
        pass

    def test_delete_incoming_text_by_id(self):
        """
        Test case for delete_incoming_text_by_id

        Delete Incoming Text
        """
        pass

    def test_get_incoming_text_by_id(self):
        """
        Test case for get_incoming_text_by_id

        Get Incoming Text
        """
        pass

    def test_get_incoming_texts(self):
        """
        Test case for get_incoming_texts

        List Incoming Texts
        """
        pass

    def test_get_short_codes(self):
        """
        Test case for get_short_codes

        List Shortcodes
        """
        pass

    def test_get_text_by_id(self):
        """
        Test case for get_text_by_id

        Get Text
        """
        pass

    def test_get_text_recipients_by_text_id(self):
        """
        Test case for get_text_recipients_by_text_id

        Get Text Recipients
        """
        pass

    def test_get_texts(self):
        """
        Test case for get_texts

        List Texts
        """
        pass


if __name__ == '__main__':
    unittest.main()
