# coding: utf-8

"""
    DialMyCalls API

    The DialMyCalls API

    OpenAPI spec version: 2.0.1
    Contact: support@dialmycalls.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import dialmycalls_client
from dialmycalls_client.rest import ApiException
from dialmycalls_client.apis.calls_api import CallsApi


class TestCallsApi(unittest.TestCase):
    """ CallsApi unit test stubs """

    def setUp(self):
        self.api = dialmycalls_client.apis.calls_api.CallsApi()

    def tearDown(self):
        pass

    def test_cancel_call_by_id(self):
        """
        Test case for cancel_call_by_id

        Cancel Call
        """
        pass

    def test_create_call(self):
        """
        Test case for create_call

        Create Call
        """
        pass

    def test_get_call_by_id(self):
        """
        Test case for get_call_by_id

        Get Call
        """
        pass

    def test_get_call_recipients_by_call_id(self):
        """
        Test case for get_call_recipients_by_call_id

        Get Call Recipients
        """
        pass

    def test_get_calls(self):
        """
        Test case for get_calls

        List Calls
        """
        pass


if __name__ == '__main__':
    unittest.main()
