# coding: utf-8

"""
    DialMyCalls API

    The DialMyCalls API

    OpenAPI spec version: 2.0.1
    Contact: support@dialmycalls.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ContactAttributes(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, phone=None, firstname=None, lastname=None, email=None):
        """
        ContactAttributes - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'phone': 'str',
            'firstname': 'str',
            'lastname': 'str',
            'email': 'str'
        }

        self.attribute_map = {
            'phone': 'phone',
            'firstname': 'firstname',
            'lastname': 'lastname',
            'email': 'email'
        }

        self._phone = phone
        self._firstname = firstname
        self._lastname = lastname
        self._email = email

    @property
    def phone(self):
        """
        Gets the phone of this ContactAttributes.
        Contact's phone number.

        :return: The phone of this ContactAttributes.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """
        Sets the phone of this ContactAttributes.
        Contact's phone number.

        :param phone: The phone of this ContactAttributes.
        :type: str
        """

        self._phone = phone

    @property
    def firstname(self):
        """
        Gets the firstname of this ContactAttributes.
        Contact's first name.

        :return: The firstname of this ContactAttributes.
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """
        Sets the firstname of this ContactAttributes.
        Contact's first name.

        :param firstname: The firstname of this ContactAttributes.
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """
        Gets the lastname of this ContactAttributes.
        Contact's last name.

        :return: The lastname of this ContactAttributes.
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """
        Sets the lastname of this ContactAttributes.
        Contact's last name.

        :param lastname: The lastname of this ContactAttributes.
        :type: str
        """

        self._lastname = lastname

    @property
    def email(self):
        """
        Gets the email of this ContactAttributes.
        Contact's email address.

        :return: The email of this ContactAttributes.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this ContactAttributes.
        Contact's email address.

        :param email: The email of this ContactAttributes.
        :type: str
        """

        self._email = email

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
