# coding: utf-8

"""
    DialMyCalls API

    The DialMyCalls API

    OpenAPI spec version: 2.0.1
    Contact: support@dialmycalls.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class CreateAccessAccountParameters(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, email=None, password=None, name=None):
        """
        CreateAccessAccountParameters - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'email': 'str',
            'password': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password',
            'name': 'name'
        }

        self._email = email
        self._password = password
        self._name = name

    @property
    def email(self):
        """
        Gets the email of this CreateAccessAccountParameters.
        (Required)  The email address for this access account.

        :return: The email of this CreateAccessAccountParameters.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this CreateAccessAccountParameters.
        (Required)  The email address for this access account.

        :param email: The email of this CreateAccessAccountParameters.
        :type: str
        """

        self._email = email

    @property
    def password(self):
        """
        Gets the password of this CreateAccessAccountParameters.
        (Required)  The password for this access account. Requirements: 8 characters, 1 digit, 1 upper case character.

        :return: The password of this CreateAccessAccountParameters.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this CreateAccessAccountParameters.
        (Required)  The password for this access account. Requirements: 8 characters, 1 digit, 1 upper case character.

        :param password: The password of this CreateAccessAccountParameters.
        :type: str
        """

        self._password = password

    @property
    def name(self):
        """
        Gets the name of this CreateAccessAccountParameters.
        (Required)  The name for this access account.

        :return: The name of this CreateAccessAccountParameters.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreateAccessAccountParameters.
        (Required)  The name for this access account.

        :param name: The name of this CreateAccessAccountParameters.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
